name: Build for MacOS Monterey 12 (x64)

on: workflow_call

jobs:
  build-x64-macos-12:
    runs-on: macos-12
    steps:
      - name: Install Elixir
        run: brew install elixir
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build release
        run: |
          export MIX_ENV=prod
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only prod
          mix compile
          mix assets.deploy
          mix release
      - name: Create release tarball
        run: tar -cvzf hyacinth-x64-macos-12.tar.gz hyacinth
        working-directory: _build/prod/rel
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: hyacinth-x64-macos-12
          path: _build/prod/rel/hyacinth-x64-macos-12.tar.gz
