name: Build for CentOS 7 (x64)

on: workflow_call

jobs:
  build-x64-centos-7:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:
      - name: Install dnf
        run: yum -y install dnf
      - name: Install Erlang/OTP
        run: |
          dnf -y install wget
          wget https://packages.erlang-solutions.com/erlang-solutions-2.0-1.noarch.rpm
          dnf -y install erlang-solutions-2.0-1.noarch.rpm
          dnf -y install esl-erlang
      - name: Install precompiled Elixir
        run: |
          dnf -y install unzip
          wget https://github.com/elixir-lang/elixir/releases/download/v1.14.0/elixir-otp-24.zip
          mkdir ~/elixir
          unzip elixir-otp-24.zip -d ~/elixir
      - name: Define en_US.UTF-8 locale
        run: |
          localedef -c -f UTF-8 -i en_US en_US.UTF-8
      - name: Install dev tools
        run: dnf -y install gcc make glibc-devel
      - name: Install devtoolset to get gcc 8
        run: |
          dnf -y install centos-release-scl
          dnf -y install devtoolset-8-gcc
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build release
        run: |
          source /opt/rh/devtoolset-8/enable
          export LC_ALL=en_US.UTF-8
          export PATH="$PATH:$HOME/elixir/bin"
          export MIX_ENV=prod
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only prod
          mix compile
          mix assets.deploy
          mix release
      - name: Create release tarball
        run: tar -cvzf hyacinth-x64-centos-7.tar.gz hyacinth
        working-directory: _build/prod/rel
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: hyacinth-x64-centos-7
          path: _build/prod/rel/hyacinth-x64-centos-7.tar.gz
